spring:
    banner:
      location: banner.txt
    data.mongodb:
      host: localhost
      port: 27017
      database: library
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: beans
  endpoint:
    health:
      show-details: always
info:
  application:
    name: spring-actuator
    description: spring boot actuator application
    version: 1.0
logging:
  file: test.log

