spring:
    banner:
      location: banner.txt
    data.mongodb:
      host: localhost
      port: 27017
      database: library
    batch:
      job.enabled: false
    datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/library
      username: postgres
      password: 123
      platform: postgresql
      validationQuery: SELECT 1
      schema: classpath:/schema.sql
