spring:
    banner:
      location: banner.txt
    data.mongodb:
      host: 192.168.99.100
      port: 27017
      database: library
    batch:
      job.enabled: false
    datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/library
      username: postgres
      password: 123
      platform: postgresql
      validationQuery: SELECT 1
      schema: classpath:/schema.sql
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: beans
  endpoint:
    health:
      show-details: always
info:
  application:
    name: spring-actuator
    description: spring boot actuator application
    version: 1.0
logging:
  file: test.log

