insert into genre (id, `genre`) values (10,'Фантастика');
insert into genre (id, `genre`) values (20, 'Боевик');
insert into genre (id, `genre`) values (30, 'Стихи');
insert into author (id, `fio`) values (10, 'Пушкин Александр Сергеевич');
insert into author (id, `fio`) values (20, 'Лукьяненко Сергей Васильевич');
insert into author (id, `fio`) values (30, 'Эльтеррус Иар');
insert into book (id, `title`,genre_id,author_id) values (10, 'Отзвуки серебряного ветра',10,30);
insert into book (id, `title`,genre_id,author_id) values (20, 'Время черных звезд',10,30);
insert into book (id, `title`,genre_id,author_id) values (30, 'Ночной дозор',20,20);
insert into book (id, `title`,genre_id,author_id) values (40, 'Пушкин. Сборник стихов',30,10);
insert into comment (id, `text`,book_id) values (1, 'Очень интересная книга',10);
